import{a as w,S as v,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const q="51904877-a497cebd24b125b23f704ea34",B="https://pixabay.com/api/";async function h(o,n=1,s=15){const t={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:s};return(await w.get(B,{params:t})).data}const d=document.querySelector(".gallery");document.querySelector(".loader");document.querySelector(".load-more");let M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function f(o,n=!1){const s=o.map(({webformatURL:t,largeImageURL:e,tags:r,likes:c,views:E,comments:S,downloads:R})=>`
    <a href="${e}" class="gallery-item">
      <div class="photo-card">
        <img src="${t}" alt="${r}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${c}</p>
          <p><b>Views:</b> ${E}</p>
          <p><b>Comments:</b> ${S}</p>
          <p><b>Downloads:</b> ${R}</p>
        </div>
      </div>
    </a>`).join("");n?d.insertAdjacentHTML("beforeend",s):d.innerHTML=s,M.refresh()}function D(){d.innerHTML=""}function m(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function p(){document.querySelector(".load-more").classList.remove("hidden")}function y(){document.querySelector(".load-more").classList.add("hidden")}let u="",i=1;const l=15,L=document.querySelector("#search-form"),b=document.querySelector(".load-more");console.log("DEBUG: searchForm =",L);console.log("DEBUG: loadMoreBtn =",b);L.addEventListener("submit",O);b.addEventListener("click",P);async function O(o){o.preventDefault(),console.log("DEBUG: onSearch triggered ✅");const n=o.currentTarget.elements.searchQuery;if(!n){console.error("❌ ERROR: searchQuery input not found");return}const s=n.value.trim();if(!s){a.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}u=s,i=1,D(),y(),m();try{const t=await h(u,i,l);if(console.log("DEBUG: fetchImages response =",t),!t||!t.hits||t.hits.length===0){a.warning({title:"No results",message:"Sorry, no images found. Try another search!",position:"topRight"});return}f(t.hits);const e=Math.ceil(t.totalHits/l);i<e?p():a.info({title:"End of results",message:"You have reached the end of search results.",position:"topRight"})}catch(t){console.error("❌ ERROR in onSearch:",t),a.error({title:"Error",message:"Something went wrong while fetching data.",position:"topRight"})}finally{g()}}async function P(){console.log("DEBUG: onLoadMore triggered ✅"),i+=1,y(),m();try{const o=await h(u,i,l);console.log("DEBUG: fetchImages response (load more) =",o),f(o.hits);const n=Math.ceil(o.totalHits/l);i<n?p():a.info({title:"End of results",message:"You have reached the end of search results.",position:"topRight"}),G()}catch(o){console.error("❌ ERROR in onLoadMore:",o),a.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{g()}}function G(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
